name: Continuous Integration

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, "3.10", "3.11"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-mock
        pip install -r requirements.txt

    - name: Run basic tests
      run: |
        python -c "print('✅ Python import test successful')"
        python -c "import json; print('✅ JSON module available')"
        
    - name: Test main modules
      run: |
        python -c "
        import os
        import sys
        sys.path.append('.')
        
        # Test basic imports
        try:
            import main
            print('✅ main.py importable')
        except Exception as e:
            print(f'⚠️ main.py issue: {e}')
            
        # Test data files
        if os.path.exists('data/cases.json'):
            import json
            with open('data/cases.json') as f:
                data = json.load(f)
            print(f'✅ cases.json valid: {len(data)} entries')
        else:
            print('⚠️ data/cases.json not found')
        "

    - name: Test quality module (basic)
      run: |
        python -c "
        import os
        import ast
        
        # Basic syntax check for test_quality.py
        if os.path.exists('test_quality.py'):
            with open('test_quality.py', 'r', encoding='utf-8') as f:
                try:
                    ast.parse(f.read())
                    print('✅ test_quality.py syntax valid')
                except SyntaxError as e:
                    print(f'❌ test_quality.py syntax error: {e}')
                    exit(1)
        else:
            print('⚠️ test_quality.py not found')
        "
        
  build:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Project structure verification
      run: |
        echo "📁 Project structure:"
        find . -name "*.py" -type f | head -10
        echo "📊 Python files count: $(find . -name "*.py" -type f | wc -l)"
